[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm-9_x']

[phases.install]
cmds = ['pnpm install --no-frozen-lockfile']

[phases.build]
cmds = [
    'echo "Building Medusa with dummy env vars..."',
    'DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy" JWT_SECRET="dummy" COOKIE_SECRET="dummy" pnpm run build'
]

[start]
cmd = './start.sh'

[variables]
NODE_ENV = 'production'